### PR TITLE
fix(deps): peerDependencies

### PR DESCRIPTION
**Pull request by tiamo**

### CODE REVIEW

**Comment by tiamo** [comment]
You have already included "@solana/wallet-adapter-wallets": "^0.16.1" to dev dependencies. pnpm always uses old version from the "peerDependencies".

**Comment by tiamo** [comment]
fixed with "@solana/wallet-adapter-wallets": "^0.15 | ^0.16"

**Comment by tiamo** [comment]
strange behaviour, new project works well with current peer dependencies

**Comment by tiamo** [comment]
This PR will be helpful to prevent warnings like this one:

 WARN  Issues with peer dependencies found
.
└─┬ solana-wallets-vue
  └── ✕ unmet peer @solana/wallet-adapter-wallets@^0.15: found 0.16.6

**Comment by lorisleiva** [comment]
Makes sense 🙆‍♂️

**Pull request merged**
