### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by Aanhane**
This is to tackle some recent issues with the wallet adapter package. Works on the demo site but I'm struggling to test it properly as a package. Any guidance on that would be appreciated, then I will also add it to a CONTRIBUTE.md if that's ok :). 

dependencies updated:
-   "@solana/wallet-adapter-base": "^0.9.5" > **"^0.9.16"**

devDepencies updated:
-  "@solana/wallet-adapter-wallets": "^0.17.0" > **"^0.18.7"** 

peerDepencies updated:
-  "@solana/wallet-adapter-wallets": "^0.17.0" > **"^0.18.7"**

### CODE REVIEW

**Comment by DjilanoS** [comment]
> Hi there 👋
> 
> Thanks for that! This is a very difficult library to create automated tests for by nature so sadly I use the example app all the time to ensure everything still works.
> 
> One thing I've noticed is that the auto-connect feature doesn't seem to work here. Might not have anything to do with this PR but when refreshing the page after connecting a wallet, it should automatically reconnect to it.

Hi @lorisleiva,
I do think however that most of us would like to have a working SignTransaction rather than a working auto-connect upon page refresh. 

For example; Your example of sending 1 lamport doesn't work as the Sign Transaction stopped working.

**Comment by lorisleiva** [comment]
Fair point! I wanted to make sure this was not caused by this dependency bump. Thanks for that.

**Comment by lorisleiva** [comment]
@DjilanoS I've published a new version with this change, would you be able to let me know if that fixed the `SignTransaction` issues?

**Comment by DjilanoS** [comment]
> @DjilanoS I've published a new version with this change, would you be able to let me know if that fixed the `SignTransaction` issues?

Just updated the package and tried calling a signTransaction function: 

image

```
  const sendOneLamport = async () => {
    const connection = new Connection(clusterApiUrl('devnet'))
    const { publicKey, sendTransaction } = useWallet();
    const randomAddr = Keypair.generate().publicKey
    if (!publicKey.value) return;

    console.log('pubkey ', publicKey.value)
    console.log('randomAddr ', randomAddr)

    const transaction = new Transaction().add(
      SystemProgram.transfer({
        fromPubkey: publicKey.value,
        toPubkey: randomAddr,
        lamports: 1,
      })
    );
    
    const latestBlockHash = await connection.getLatestBlockhash();

    const signature = await sendTransaction(transaction, connection);
    await connection.confirmTransaction({
      blockhash: latestBlockHash.blockhash,
      lastValidBlockHeight: latestBlockHash.lastValidBlockHeight,
      signature: signature
    });
  };
```

**Comment by DjilanoS** [comment]
@lorisleiva by the looks of it, it seems to be narrowed down to Phantom Wallet Adapter only.
Solflare for example works just fine 
image

**Comment by lorisleiva** [comment]
It's strange though because the demo seems to be working with the latest version using Phantom. 🤔 

https://solana-wallets-vue-demo.netlify.app/

**Comment by Aanhane** [comment]
I think the auto-connect broke upon updating `wallet-adapter-base`. I would like to debug this.

@lorisleiva any tips on where I can find information on how to test my forked version? I tried using my git repo url and that works to some extent; but I get a 'cannot resolve Buffer' error. I think it's due to the fact I'm missing some steps that `npm prepublish` does for example? Testing my forked version will allow me to test this by hand and fix any bugs that come out of it. 

For now, maybe we can add a sign transaction button to the demo? Then we can open a PR and test by making changes and have at least a test-setup that also includes the sign transaction functionality?

**Comment by Aanhane** [comment]
> @lorisleiva by the looks of it, it seems to be narrowed down to Phantom Wallet Adapter only. Solflare for example works just fine

@DjilanoS did you also update the `@solana/wallet-adapter-wallets` package in your project?

**Comment by Aanhane** [comment]
For the auto-reconnect, maybe we need a fix like this one that was done on the Svelte Package?
https://github.com/svelte-on-solana/wallet-adapter/commit/69e4ee893d3073d4c774a9af2e1674c6fcfa6fda

**Comment by mdurao** [comment]
I'm getting the autoConnect issue with Phantom for Android.
Strangely, same codebase works ok with IOS and Web Extension.

If I disable the autoConnect, everything works ok.

@lorisleiva , is there anything I can do on my side to fix this?

**Pull request merged**
